version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: greenlight
    user: "postgres"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
